#pragma once

#include "ggml-backend.h"
#include "ggml-cpp.h"
#include "utils.h"
#include <string>

/*
    ContextManager is responsible for maintaining ggml_context, backend, buffer, etc.
    These do not change significantly across different models.
*/
class ContextManager {
public:
  ContextManager() : ContextManager("CPU", 1, GGML_DEFAULT_GRAPH_SIZE) {}
  ContextManager(const std::string &dev_name, int n_threads = 1,
                 int max_nodes = GGML_DEFAULT_GRAPH_SIZE);
  ContextManager(const ContextParams &params)
      : ContextManager(params.device_name, params.n_threads, params.max_nodes) {
  }

  inline void synchronize() { ggml_backend_sched_synchronize(sched_.get()); }
  static ggml_backend_t try_init_backend(enum ggml_backend_dev_type type);

  // protected:
  bool create_backend(const std::string &dev_name, int n_threads);
  bool create_scheduler();
  bool alloc_tensors();

  // Used as initialization parameters for gguf and stores weight info. Later takes ownership of ctx_meta generated by ModelLoader.
  ggml_context_ptr ctx_data_ = nullptr;
  // Allocates memory on the specified backend based on ctx_data_
  ggml_backend_buffer_ptr buffer_ = nullptr;

  // Stores cgraph, nodes, leafs, hash and other states.
  // This state is created by the graph object and released after the graph is done. Actual data is saved in buf_compute_meta.
  ggml_context_ptr ctx_compute_ = nullptr;

  // Used for graph context construction, memory address corresponding to ctx_compute, not released. ctx_compute_ can be released early, data is still saved in buf_compute_meta_
  std::vector<uint8_t> buf_compute_meta_;

  ggml_backend_ptr backend_cpu_ = nullptr;
  ggml_backend_ptr backend_ = nullptr;
  std::vector<ggml_backend_t> backend_ptrs_;
  std::vector<ggml_backend_buffer_type_t> backend_buft_;

  ggml_backend_sched_ptr sched_ = nullptr;

  ggml_cgraph *gf_ = nullptr;
  // Recommended to set this value after build_graph by checking the node count in cgraph object.
  int max_nodes_ = GGML_DEFAULT_GRAPH_SIZE; // 8192

  // // Some additional properties
  // gguf_context_ptr ctx_gguf_ = nullptr;

  // for debugging
  bool debug_graph_ = false;
  std::vector<ggml_tensor *> debug_print_tensors_;
};
